### ISSUE TITLE
[P0 Audit] Public Surface / Package Version / Core Extraction — 6 Remaining Items

### ISSUE THREAD

**Issue by AhaSparkCoach** [aikdna/kdna#101]
# [P0 Audit] Public Surface / Package Version / Core Extraction — 6 Remaining Items

**Audit period**: 2026-06-17 ~ 2026-06-18 (7 tracking passes across 25 repos)
**Auditor**: external (this issue)
**Scope**: post main-repo commit `a912df1` (cli-v1 54/54 PASS) and kdna-cli 0.23.0 published

---

## TL;DR

Most of these are 1-line package.json changes. One needs a maintainer decision on intent.
One is a planned v0.24.0 deliverable, not urgent.

4 items are immediate (1-line changes). 1 item needs maintainer input. 1 item is roadmap.

---

## Findings

| #  | Item                                                                              | Repo                          | File:Line                                              | Severity    | Suggested action                                                              | Unblocks                                |
|----|-----------------------------------------------------------------------------------|-------------------------------|--------------------------------------------------------|-------------|-------------------------------------------------------------------------------|-----------------------------------------|
| 1  | `kdna-studio-core` declares `@aikdna/kdna-core: ^0.9.1`                           | aikdna/kdna-studio-core       | `package.json:27`                                       | 🔴 P0       | Bump to `^0.10.0` (1 line)                                                    | Monorepo kdna-cli pretest + v07 load   |
| 2  | `kdna-skills/mcp-server` declares `@aikdna/kdna-core: ^0.7.2`                      | aikdna/kdna-skills            | `mcp-server/package.json` (deps)                        | 🔴 P0       | Bump to `^0.10.0` (1 line)                                                    | mcp-server tool                         |
| 3  | kdna monorepo devDeps `@aikdna/kdna-cli: ^0.19.0`                                 | aikdna/kdna                   | `package.json:devDependencies`                         | 🟡 P0       | Bump to `^0.23.0` (1 line)                                                    | Documentation precision                 |
| 4  | `.github/workflows/registry-validate.yml` named "Protocol Fixture Registry Validate" | aikdna/kdna                   | `.github/workflows/registry-validate.yml`              | 🟡 P0       | Rename workflow to `legacy-fixture-validate.yml`                             | P0 public surface (workflow name shows in GH UI) |
| 5  | `kdna-studio-cli` README L1/L3 self-claims "Official"                             | aikdna/kdna-studio-cli        | `README.md:1`, `README.md:3`                           | 🟡 discuss  | Maintainer decision: align with kdna-studio-core 1.5.2 "Official" usage? Or change to "Studio-compatible" per audit checklist §3.2? | P1 toolchain wording consistency      |
| 6  | kdna-cli 0.23.0 npm tarball still contains duplicated `src/v1-cli.js` (~700 lines) | aikdna/kdna-cli               | `src/v1-cli.js`                                         | 🟡 Phase 9 | Plan: v0.24.0 deletes `src/v1-cli.js`, requires `@aikdna/kdna-core/src/v1`   | Core extraction completion (main-repo kdna.js already done in `a912df1`) |

---

## Test status (post main-repo `a912df1`)

- ✅ **Main repo cli-v1: 54/54 PASS** (was 32, +22 fixture matrix)
- ✅ Main repo `core-smoke`, `format:check`, `validate:*` — all pass
- 🔴 **kdna-cli pretest-smoke: FAIL** — blocked by #1 (`installed=0.9.1 vs declared=^0.10.0`)
- 🔴 kdna-cli `v07-commands.test.js`: 9 fail
  - 1 from v0.22.4 help restructure (expected regression, test code needs `kdna help advanced`)
  - 7 from stale assets (`@aikdna/writing` 0.7.3, `agent_safety` 0.7.6, `prompt_diagnosis` 0.7.6) — kdna-core 0.9.1 strict validation
  - 1 from `TypeError: isV1SourceDir is not a function` (kdna-core 0.9.1 missing this export)
- 🔴 kdna-cli `v012-commands.test.js`: 7 fail (4 help regression + 3 stale)
- 🔴 kdna-cli `asset-store.test.js`: 2 fail (stale assets)

---

## Suggested priority order

1. **#1** — `kdna-studio-core` `^0.9.1` → `^0.10.0` (single highest ROI: 1 line unlocks pretest + most v07 fails)
2. **#2** — `mcp-server` `^0.7.2` → `^0.10.0` (1 line, parallel to #1)
3. **#3** — monorepo devDeps `^0.19.0` → `^0.23.0` (1 line)
4. **#4** — workflow rename (1 commit)
5. **#5** — `kdna-studio-cli` README — needs maintainer input first
6. **#6** — v0.24.0 core extraction — planned, not urgent

---

## Notes on items that may be intentionally preserved

- **#5** (`kdna-studio-cli` "Official" wording) may be intentional — the wording is **consistent** with:
  - `kdna-studio-core 1.5.2` description: "**Official** KDNA Studio Core SDK for..."
  - Main repo `README.md` §7 "Official KDNA toolchain" table lists KDNA Studio as a component
  - All 4 of these use "Official" to mean "toolchain component defined in main repo", **not** "open protocol / reference implementation" (which is what audit checklist §3.2 prohibits)
  
  If the team considers this self-consistent, item #5 is **not** an issue. Otherwise, change README L1/L3 to "Studio-compatible authoring entry" (matching pre-v1 wording).

- **#4** (`kdna-registry` CI workflow still active) may be intentional for backward compatibility (existing users still use `kdna install` from legacy registry). Workflow rename is a minimal change that doesn't break the workflow, only the workflow display name.

---

## What was already fixed in this audit period (2026-06-17 ~ 2026-06-18)

For context — 50+ commits across 10 repos in this period:

### P0 public surface
- Removed `judgment-protocol` keyword from 6 npm packages: `@aikdna/kdna-cli`, `@aikdna/kdna`, `@aikdna/kdna-vscode`, `@aikdna/kdna-studio-core`, `@aikdna/kdna-workpack`, `@aikdna/kdna/packages/kdna`
- kdna-vscode `displayName`: "KDNA Protocol Tools" → "KDNA Developer Tools"
- kdna-vscode `description`: removed "Trusted .kdna creation belongs to Studio-compatible compilers"
- kdna-studio-core 1.5.2 `description`: removed "trusted .kdna assets" → "Official KDNA Studio Core SDK..."
- kdna-cli `help`: split into default/advanced/legacy layers; default no longer lists `install`/`info`/`registry`/`badge`/`publish`

### P0 archive / internal language
- 13 historical docs got "Historical / legacy" banners:
  - kdna-registry inner 7 docs (CHANGELOG, OFFICIAL_REPUBLISH, CONTRIBUTING, CODE_OF_CONDUCT, SECURITY, PUBLISHING, registry-policy)
  - kdna main 3 archive docs (`docs/archive/kdna-registry-ci.md`, `docs/archive/kdna-compatible-certification.md`, `specs/archive/kdna-registry.md`)
  - 3 release-board / release-gate / safety docs got banners
- 4 P3 active internal language items synthesized in `kdna/docs/GOVERNANCE.md`:
  - `Kdna内部思考 / KDNA 协议升级工作计划 2026-06-16.md §4.2` → `private-planning-folder/private-upgrade-plan.md §4.2`
  - `/Users/AI/K/OPEN/kdna-studio-core` → `/Users/example/private-workspace/kdna-studio-core`
  - `backup-before-reset` → `local-backup-tag-not-pushed`
  - `AhaSparkCoach / AIBUBB技术团队` → `private-maintainer / private-team`
  - `不要在外部审计前再引入复杂 book-derived 变量` → `A private conversation directive: defer complex book-derived variables`
  - `atomspeak-kdna-v4.0` → `private-domain-version-string`
  - `the反审计 file's 缺口三` → `private-review-doc finding #3`
- `kdna/specs/RFC-0013-judgment-asset-lifecycle.md:626`: "internal reverse-audit (~500 lines, not in repo)" / "internal review of recommendations (~1778 lines, not in repo)" → "maintainer review notes" / "maintainer recommendation review"
- `kdna/docs/audits/2026-06-16-rfc-0013-audit-note.md`: 7 instances of "direct-push bypass" / "Local backup tag" / "stale local commit" → "direct push outside PR flow" / "local backup marker" / "local-only commit not present on remote"
- `kdna/docs/audits/rfc-0013-implementation-evidence-pack.md:188`: "The validation signal is **local-only**" → "marked as historical snapshot"
- `public-internal-language-scan.md`: status `PASS` → `CONDITIONAL PASS` (honest reclassification after synthesis)

### P1 toolchain wording
- `kdna-cli` README: removed "the protocol / the toolchain / the catalog / official reference implementation"; removed "Open Source and Commercial Boundary" section; replaced "Product Matrix" with "Official toolchain components"
- `kdna-workpack` README + package.json + `docs/work-pack-relation-matrix.md`: replaced "open packaging standard" with "experimental KDNA workflow package format"
- `kdna-workpack/docs/work-pack-governance.md`: "## 6. Official Badge Program" → "## 6. Historical / Experimental Governance Notes" + banner
- `kdna-skills/kdna-loader/SKILL.md`: "trusted .kdna assets require Human Lock and Studio-compatible..." → "formal .kdna assets are created through the official KDNA Studio toolchain"

### Tooling (Phase 7 + Phase 9)
- kdna-cli 0.22.0: v1 route on global CLI (no monorepo clone needed)
- kdna-cli 0.22.4: `kdna help` default/advanced/legacy restructure
- kdna-cli 0.22.4: `kdna demo minimal <dir>` (offline first-run fixture, no registry)
- kdna-cli 0.23.0: `kdna load <path> --profile={index,compact,scenario,full} --as={json,prompt}`
- kdna-cli 0.23.0: kdna-core dep `^0.9.1` → `^0.10.0`
- `@aikdna/kdna-core` 0.9.1 → 0.10.0: official shared v1 module `src/v1/index.js` (776 lines, `inspect`/`validate`/`pack`/`unpack`/`loadV1` + `FORBIDDEN_OUTPUT_TERMS`)
- Main repo `packages/kdna/bin/kdna.js`: `load` command now uses `@aikdna/kdna-core/src/v1.loadV1` (core extraction main-repo complete)
- 22 new tests in `tests/cli-v1/v1-fixture-matrix.test.js` + 3 invalid fixtures (`invalid-missing-manifest`, `invalid-missing-payload`, `invalid-bad-checksum`)

### Documentation
- `docs/try-kdna.md` (new, 50 lines) — 5-min first-run guide
- `docs/15-minute-agent-guide.md` (new, 92 lines)
- `docs/30-minute-authoring-guide.md` (new, 107 lines)
- `docs/core/load-profiles.md` (new, 158 lines) — normative `index`/`compact`/`scenario`/`full` profile contract
- `docs/audits/core-extraction-readiness.md` (new, 84 lines)
- `docs/audits/public-internal-language-scan.md` (new, 56 lines, CONDITIONAL PASS)
- `docs/audits/public-surface-p0-final-check.md` (new, 58 lines, PASS)
- `docs/releases/kdna-core-v1-global-cli-baseline.md` (new, 60 lines)
- `docs/status.md` (updated, "v1 route resolved in 0.22.0", "npm descriptions resolved in 0.22.x / 0.3.3 / 1.5.2")

---

## Engagement

- If maintainers want this split into individual sub-issues, comment below.
- If item #5 needs a separate Discussion thread, say so.
- If any of the "may be intentional" notes are wrong, point me at the relevant design doc / RFC.

cc: anyone tracking KDNA Core v1 readiness

**Comment by aikdna** [comment]
Thanks — this audit is useful and matches the current KDNA Core v1 readiness cleanup plan.

We agree with items #1–#4 and have split them into small version / public-surface alignment commits:

- **#1 kdna-studio-core** → @aikdna/kdna-core ^0.10.0 (committed, pushed)
- **#2 kdna-skills/mcp-server** → @aikdna/kdna-core ^0.10.0 (committed, pushed)
- **#3 kdna monorepo devDep** → @aikdna/kdna-cli ^0.23.0 (committed, pushed, closes #102)
- **#4 registry fixture workflow display name** → changed to 'Legacy fixture validate (registry/domains.json)' (committed, pushed, closes #103)

For item **#5**:
We keep 'Official' in kdna-studio-cli README when it refers to an official KDNA toolchain component. Added a clarifying sentence: 'Official means this package is part of the KDNA official toolchain. It does not imply content trust, asset endorsement, registry status, or quality rating.'

For item **#6**:
Agreed. Removing duplicated kdna-cli src/v1-cli.js and relying fully on the shared @aikdna/kdna-core v1 module is tracked for kdna-cli v0.24.0 core extraction, separate from these immediate cleanup commits.

**Comment by aikdna** [comment]
Updated 2026-06-18.

All 6 items from this audit have been addressed:

- **#1 kdna-studio-core → @aikdna/kdna-core ^0.10.0**: ✓ Done. Published at 1.5.2 → already using ^0.10.0.
- **#2 kdna-skills/mcp-server → @aikdna/kdna-core ^0.10.0**: ✓ Done. Published.
- **#3 kdna monorepo devDep → @aikdna/kdna-cli ^0.23.0**: ✓ Done. Closed #102.
- **#4 registry fixture workflow display name**: ✓ Done. Closed #103.
- **#5 kdna-studio-cli 'Official' wording**: ✓ Retained with clarification: 'Official means this package is part of the KDNA official toolchain. It does not imply content trust, asset endorsement, registry status, or quality rating.'
- **#6 kdna-cli v0.24.0 core extraction**: ✓ Done. src/v1-cli.js removed in kdna-cli@0.24.0. CLI now relies fully on shared @aikdna/kdna-core@0.11.0. No duplicate v1 implementation in npm tarball.

Current pipeline status documented in docs/releases/kdna-core-v1-official-pipeline-baseline.md.

**Comment by aikdna** [comment]
Pipeline closure update (2026-06-18): this umbrella audit is now superseded by the v1 closure work.

Current resolved state:

- kdna-studio-core dependency line moved past the original ^0.9.x finding; published @aikdna/kdna-studio-core@1.5.3 depends on @aikdna/kdna-core ^0.11.1.
- kdna-skills MCP dependency moved past the original ^0.7.x finding; MCP server now depends on @aikdna/kdna-core ^0.11.1 plus runtime ajv / ajv-formats, and @aikdna/kdna-mcp-server@0.1.0 has registry clean-install proof.
- kdna monorepo compatibility package now depends on @aikdna/kdna-cli ^0.25.0 and @aikdna/kdna-core ^0.11.1; duplicate packages/kdna/src/v1-cli.js was removed.
- The workflow naming / stale registry-surface issue has been reframed in current docs as legacy registry boundary.
- Studio CLI wording now treats Studio as the current v1 authoring/export path without claiming signature/encryption/private assets.
- The old kdna-cli duplicate v1 implementation finding is superseded by the shared Core extraction and @aikdna/kdna@0.9.0 publication.

Additional evidence now exists in:

- docs/releases/kdna-core-v1-official-pipeline-baseline.md
- docs/audits/studio-export-e2e-status.md
- docs/audits/flagship-v1-migration-hardening-verification.md
- docs/audits/flagship-v1-migration-blocker-summary.md

Closing this umbrella issue as resolved/superseded. Remaining launch work is tracked separately as final release artifacts, website owner review, and enterprise/private-deployment work (#53).
